Adição dos posts antigos do Querido Diario
okfn-brasil/querido-diario-frontend pull request #150
Opened 2023-06-10 00:35 UTC by Winzen

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [x] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.
De #120 até  #143 

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-06-10 03:59 UTC, Winzen commented
@trevineju
Segue o PR com adição dos HTMLs dos Posts antigos.

Alguns precisam ser editados e os links das fotos ajustados, como de alguns `<a>`.

Obs:

Post 11 e 17 tinha tags `<li>` e `<ul>` e não estavam funcionando de acordo. Acabei mudando eles só para fazer o PR, mas precisam ser revisados.

Post 11 também encontramos uma imagem que tem um rodapé. Verificar melhor forma de colocar o rodapé junto a imagem.
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/94500122/3709b411-f7b7-452a-b00e-a12c05ea1a5d)

Post 17 encontramos muitos `<li>` e `<ul>`  como:
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/94500122/ee0498bf-126f-4ab7-9bd6-a7b23b905487)

Post 6 temos um direcionador para o catarse que pode ser melhor aplicado na pagina.
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/94500122/820e761c-2232-4bd3-af7b-8b8d04ac7d40)
 
Post 9 temos um video,que aqui estava pegando bem. Por hora eu só aumentei a largura dele para 100%
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/94500122/e526b038-190f-4aea-b1d4-c8003b22a71a)

Em geral é isso. Acabei não colocando os `\` nas `"` porque no teste parecia esta funcionado normal sem eles.

2023-06-24 00:01 UTC, trevineju commented
Está ótimo @Winzen!! Obrigada demaisss!! <3 

Ainda tem algumas pendências, mas foi erro meu na seleção. Posso terminar outro dia. Vou deixar aqui pra não esquecer: 
- adicionar o post 13:  https://ok.org.br/noticia/medidas-contraditorias-e-falta-de-direcionamento-a-historia-do-2o-colapso-da-saude-de-manaus-contada-pelo-diario-oficial/
- verificar numeração dos banners na Digital Ocean
- verificar os hiperlinks que direcionam para o site da OKBR e que agora devem passar a direcionar para o próprio site do QD.

2023-06-26 18:43 UTC, ogecece commented
Vi que os ids dos posts estavam sendo modificados. Como isso quebraria links atuais aos posts então seria melhor quebrar apenas o post com `id=1` e modificá-lo para `id=0` e manter os ids restantes. Tudo bem?

2023-07-07 14:07 UTC, ogecece requested changes
Jogando na roda que organizar por `post0`, `post1`, ... , `post10`, etc. deixa a ordenação confusa no sistema de arquivos. Quem topa `post0000`?

2023-07-07 14:07 UTC, ogecece commented on src/assets/pages/blogposts/post-16.html
> +<p>Lembrando que, se você é uma pessoa desenvolvedora e deseja contribuir com a integração de cidades à plataforma, pode acessar o <a href="https://github.com/okfn-brasil/querido-diario">repositório
Pode atualizar quaisquer convites do discord?

2023-07-07 19:32 UTC, trevineju commented on src/assets/pages/blogposts/post-01.html
> +<p>O Querido Diário faz a captura e análise de diários oficiais dos municípios para compreensão dos casos de dispensa de licitação. Atualmente, está presente em Goiânia e Porto Alegre, e em fase de c
tinha visto também, mas arrumei apenas no blog.json, esqueci de arrumar esse. Obrigada

2023-07-07 22:01 UTC, trevineju commented on src/assets/pages/blogposts/post-04.html
> +<p>Esses aprendizados serão levados para as futuras edições do sprint, e que podem ser interessantes para quem pretende encarar o desafio de realizar eventos similares. Confira no <a href="https://me
Só acolho o commit de sugestão pq a mudança já foi feita em https://github.com/okfn-brasil/querido-diario-frontend/pull/150/commits/aedb04a8d0b18ccb6aba848e855678968e530dbc

2023-07-07 22:01 UTC, trevineju commented on src/assets/pages/blogposts/post-16.html
> +<p>Lembrando que, se você é uma pessoa desenvolvedora e deseja contribuir com a integração de cidades à plataforma, pode acessar o <a href="https://github.com/okfn-brasil/querido-diario">repositório
feito

2023-07-07 22:07 UTC, trevineju commented on src/assets/pages/blogposts/post-04.html
> +<p>Esses aprendizados serão levados para as futuras edições do sprint, e que podem ser interessantes para quem pretende encarar o desafio de realizar eventos similares. Confira no <a href="https://me
Aliás, não adicionei a correção quando a referência era pra outra página do próprio site.

2023-07-07 22:07 UTC, trevineju commented
Não me incomodava muito com a ordenação lexicográfica, mas arrumei. Está corrigido na Digital Ocean e nas referências às imagens (https://github.com/okfn-brasil/querido-diario-frontend/pull/150/commits/4313bbbdce3e501e284870ecc7ae4160ada9feab). Só não mexi no nome dos arquivos html (de `post-00.html` para `post-0000.html`) pq como a questão era ordenação, estava ordenado.

2023-07-10 22:26 UTC, ogecece approved these changes
LGTM! @Winzen @trevineju 

![_](https://media.giphy.com/media/6STZNtl1a8qiwspycw/giphy.gif)

2023-07-10 22:26 UTC, merged