Adiciona post sobre GTs no blog do QD
okfn-brasil/querido-diario-frontend pull request #170
Opened 2023-08-29 22:30 UTC by rasrbk

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [x] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-08-29 23:58 UTC, trevineju commented
Ali no cabeçalho do PR tem uma checklist de validadores. Essa etapa serve pras próprias pessoas contribuidoras examinarem seu próprio PR antes de uma revisão.  

### Fazendo as validações: 
Em pouco tempo depois de enviar o PR, o bot do netlify vai enviar uma mensagem aqui. Nessa mensagem tem os links que vai precisar para verificar como o site do QD ficará uma vez que o PR seja aceito. 

1. Para essa validação, clica no link "😎 Deploy Preview" e navega nas páginas associadas às mudanças do PR. No caso, a página do blog e a do post 41. Dá uma olhada nas páginas, padrão do tamanho das imagens, a formatação do texto, clica nos links referenciados para ver se eles abrem corretamente. 

2. Para validar o layout em celular, mesmo no computador, basta abrir o link de preview, e apertar F12. Vai abrir uma janela na lateral da página e lá vc seleciona um ícone que tem um pc e um celular; está bem no menu superior. Ele vai gerar uma tela como a da imagem a seguir, vc pode navegar no site do QD como se fosse em celular a partir disso. 
Como o texto vc já vai ter validado no item (1), aqui só resta dar uma olhada se tudo bem também com o layout.
![Screenshot from 2023-08-29 20-46-03](https://github.com/okfn-brasil/querido-diario-frontend/assets/44185775/7f1cf40d-3f54-44c1-9148-4fe6ec4fb009)


Aí é só marcar as checkboxs como feitas uma vez que tenha feito isso.

2023-08-30 13:37 UTC, lguima requested changes
@rasrbk

2023-08-30 13:37 UTC, lguima commented on src/assets/pages/blog.json
> +      "content": "<p><em>A partir da formação de um GT voltado para implementação de melhorias no site do Querido Diário, outros dois grupos foram criados: o GT de Raspadores e o de Processamento de
> específicos(Wikipédia).

específicos. (Wikipédia)

> Calendário da comunidade.strong>

Calendário da comunidade.

> calendário público,[https://go.ok.org.br/agenda-comunidade](https://calendar.google.com/calendar/u/0/embed?src=c_56ccfa81246b120981cdb75b5d49f36701720d08fa1d119f09527be72bdcede0@group.calendar.google.com&ctz=America/Sao_Paulo)

calendário público, [https://go.ok.org.br/agenda-comunidade](https://calendar.google.com/calendar/u/0/embed?src=c_56ccfa81246b120981cdb75b5d49f36701720d08fa1d119f09527be72bdcede0@group.calendar.google.com&ctz=America/Sao_Paulo)

> GT Front-end

GT Frontend

> neste[quadro no GitHub](https://github.com/orgs/okfn-brasil/projects/22/)Atualmente,

neste [quadro no GitHub](https://github.com/orgs/okfn-brasil/projects/22/). Atualmente,

> explicado no post[Entenda como analisar sites oficiais para raspagem de dados.](https://queridodiario.ok.org.br/blog/post/30)

> vinculado ao [quadro de expansão de cidades.](https://github.com/orgs/okfn-brasil/projects/12)O GT também

vinculado ao [quadro de expansão de cidades.](https://github.com/orgs/okfn-brasil/projects/12). O GT também

explicado no post [Entenda como analisar sites oficiais para raspagem de dados.](https://queridodiario.ok.org.br/blog/post/30)

> GitHub é o[querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)

GitHub é o [querido-diario-data-processing](https://github.com/okfn-brasil/querido-diario-data-processing)

2023-09-18 12:51 UTC, trevineju commented
@lguima, como a @rasrbk precisava fazer outras coisas, nós combinamos que eu ia terminar os ajustes aqui. Solicitei sua revisão de volta.

2023-09-18 14:42 UTC, lguima approved these changes
LGTM 🚀 

@trevineju @rasrbk

2023-09-18 14:51 UTC, trevineju commented
uhu! obrigada @lguima!

2023-09-18 14:52 UTC, merged

2023-09-18 18:13 UTC, rasrbk commented
Obrigada, @trevineju e @lguima!