Adiciona postagem sobre formulário de usabilidade do Querido Diário
okfn-brasil/querido-diario-frontend pull request #183
Opened 2023-10-04 21:35 UTC by rasrbk

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [x] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-10-05 17:51 UTC, ogecece requested changes

2023-10-05 17:51 UTC, ogecece commented on src/assets/pages/blog.json
> +      "banner": "https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0044/banner-post43.png",
```suggestion
      "banner": "https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0044/banner-post44.png",
```

2023-10-05 17:57 UTC, ogecece requested changes

2023-10-05 17:57 UTC, ogecece commented on src/assets/pages/blogposts/post-44.html
> +<p><em>Responda &agrave; Pesquisa de Usabilidade do Querido Di&aacute;rio e ajude a comunidade a implementar melhorias no front-end do projeto. O prazo para responder &eacute; at&eacute; dia 17 de ou
O texto em `blog.json` não começa assim. Aqui está desatualizado ou lá?

2023-10-05 17:57 UTC, ogecece commented on src/assets/pages/blogposts/post-44.html
> +<p>O question&aacute;rio foi desenvolvido pelas pessoas da comunidade que fazem parte do grupo de trabalho (GT) focado em implementar melhorias no site do Querido Di&aacute;rio. O objetivo &eacute; c
Link de edição...

2023-10-05 21:10 UTC, trevineju commented on src/assets/pages/blogposts/post-44.html
> +<p>O question&aacute;rio foi desenvolvido pelas pessoas da comunidade que fazem parte do grupo de trabalho (GT) focado em implementar melhorias no site do Querido Di&aacute;rio. O objetivo &eacute; c
Precisa tirar o "Foundation" do parágrafo aqui também

2023-10-06 15:09 UTC, rasrbk commented on src/assets/pages/blogposts/post-44.html
> +<p><em>Responda &agrave; Pesquisa de Usabilidade do Querido Di&aacute;rio e ajude a comunidade a implementar melhorias no front-end do projeto. O prazo para responder &eacute; at&eacute; dia 17 de ou
vou corrigir.

2023-10-06 23:46 UTC, lguima requested changes
@rasrbk

2023-10-06 23:46 UTC, lguima commented on src/assets/pages/blogposts/post-44.html
> +<p>A Open Knowledge Foundation Brasil (OKBR) est&aacute; com uma enquete aberta sobre a experi&ecirc;ncia das pessoas na utiliza&ccedil;&atilde;o da iniciativa do <a href="https://queridodiario.ok.or
Pra gente garantir a acessibilidade, recomenda-se usar como texto do link uma palavra ou termo que sozinha deixe claro o contexto de para onde a pessoa será redirecionada em vez de "clique aqui".

O leitor de tela interpretaria como "Link, clique aqui", quando poderíamos usar outro texto, por exemplo "Link, formulário".

```suggestion
<p>A Open Knowledge Foundation Brasil (OKBR) est&aacute; com uma enquete aberta sobre a experi&ecirc;ncia das pessoas na utiliza&ccedil;&atilde;o da iniciativa do <a href="https://queridodiario.ok.org.br/">Querido Di&aacute;rio</a>. Responda ao <a href="https://go.ok.org.br/pesquisa-qd">formul&aacute;rio</a>, leva apenas alguns minutos.&nbsp;</p>
```

2023-10-06 23:46 UTC, lguima commented on src/assets/pages/blogposts/post-44.html
> +<p>O question&aacute;rio foi desenvolvido pelas pessoas da comunidade que fazem parte do grupo de trabalho (GT) focado em implementar melhorias no site do Querido Di&aacute;rio. O objetivo &eacute; c
Estamos usando o seguinte link para divulgação do formulário, em vez do direto do Google Forms:
- https://go.ok.org.br/pesquisa-qd

E quando formos divulgar um formulário para resposta, precisamos divulgar o link de exibição e não de edição.

Fazemos isso através do ícone de olho:
![Captura de tela 2023-10-06 203943](https://github.com/okfn-brasil/querido-diario-frontend/assets/1562097/5fada31a-20a2-49f6-8785-9fedfb9a3bbc)

Ou clicando em Enviar (Send):
![Captura de tela 2023-10-06 204015](https://github.com/okfn-brasil/querido-diario-frontend/assets/1562097/977a3e7e-ae4f-4134-9a88-d3e45d829bea)

A propósito, podem verificar a permissão de edição do formulário, eu acessei o link e tenho acesso para editar, não sei se por que estou no GT ou está aberto.

```suggestion
<p>O question&aacute;rio foi desenvolvido pelas pessoas da comunidade que fazem parte do grupo de trabalho (GT) focado em implementar melhorias no site do Querido Di&aacute;rio. O objetivo &eacute; coletar dados para fundamentar escolhas em torno do frontend do projeto. A <em>Pesquisa de Usabilidade do Querido Di&aacute;rio</em> est&aacute; no ar desde o m&ecirc;s passado, para coletar informa&ccedil;&otilde;es. O <a href="https://go.ok.org.br/pesquisa-qd">formul&aacute;rio</a> ficar&aacute; aberto at&eacute; 17 de outubro, leva de 10 a 15 minutos para responder.</p>
```

2023-10-09 18:04 UTC, tigreped commented on src/assets/pages/blogposts/post-44.html
> +<p>O question&aacute;rio foi desenvolvido pelas pessoas da comunidade que fazem parte do grupo de trabalho (GT) focado em implementar melhorias no site do Querido Di&aacute;rio. O objetivo &eacute; c
Valeu a observação sobre a permissão do form para edição, Lucas, vamos verificar isso.

2023-10-09 19:16 UTC, merged