Abre página para Termo de Privacidade em Inglês
okfn-brasil/querido-diario-frontend pull request #188
Opened 2023-10-06 21:32 UTC by trevineju

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [ ] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [ ] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-10-09 22:56 UTC, trevineju commented on src/assets/pages/privacy.json
> +            "Em resumo, a tecnologia por trás do QD funciona da seguinte forma: robôs fazem diariamente a varredura dos sites publicadores de diários oficiais que já foram <a target=\"_blank\" href=\
Validei essas alterações no texto e hiperlink com Fernanda

2023-10-09 22:57 UTC, trevineju commented on src/assets/pages/privacy.json
> +          "title": "A quem pertencem as informações disponibilizadas pelo Querido Diário?",
Troquei apenas esse pq fiquei com a impressão que nos títulos das categorias/seções era melhor ficar por extenso, aí no corpo deixei as abreviações

2023-10-09 22:59 UTC, trevineju commented on src/assets/pages/privacy-en_US.json
> +            "The comptroller of the data available in QD is OKBR. Any questions, requests and suggestions can be sent to the email contact AT serenata.ai."
```suggestion
            "The comptroller of the data available in QD is OKBR. Any questions, requests and suggestions can be sent to the email contato AT serenata.ai."
```

2023-10-10 12:23 UTC, ogecece requested changes
@trevineju validei aqui pode mudar a nota de rodapé para avisar que esta é a versão 2.1 do termo e a data da última atualização sendo hoje?

2023-10-10 12:23 UTC, ogecece commented on src/assets/pages/privacy.json
> +            "<a target=\"_blank\" href=\"https://queridodiario.ok.org.br/tecnologia\">Nesta seção</a>, é possível conhecer mais detalhes técnicos sobre a arquitetura da plataforma. Todo o código está
Só muda o `type=all` pra `type=source`
```suggestion
            "<a target=\"_blank\" href=\"https://queridodiario.ok.org.br/tecnologia\">Nesta seção</a>, é possível conhecer mais detalhes técnicos sobre a arquitetura da plataforma. Todo o código está disponível de forma aberta em <a target=\"_blank\" href=\"https://github.com/orgs/okfn-brasil/repositories?q=querido-diario&type=source\">repositórios públicos no GitHub</a> e, portanto, pode ser auditado por qualquer pessoa.",
```

2023-10-10 13:14 UTC, merged