Limita a data de fim do campo de período ao ano atual
okfn-brasil/querido-diario-frontend pull request #189
Opened 2023-10-07 07:20 UTC by MoisesMsa

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [x] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
#20 

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-10-07 10:28 UTC, rennerocha commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(this.maxDate.getFullYear(), 11, 31);
**sugestão** Não faz sentido tentar buscar nenhuma data no futuro. O que acha de colocar como limite a data de hoje?

2023-10-07 11:29 UTC, MoisesMsa commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(this.maxDate.getFullYear(), 11, 31);
Opa, Renne, atualizado.

2023-10-07 12:55 UTC, ogecece requested changes

2023-10-07 12:55 UTC, ogecece commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(currentYear, currentMont, currentDay);
Só pra corrigir um errinho besta de digitação
```suggestion
    const currentMonth = this.maxDate.getMonth();
    const currentDay = this.maxDate.getDate();

    this.maxDate = new Date(currentYear, currentMonth, currentDay);
```

2023-10-07 13:04 UTC, MoisesMsa commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(currentYear, currentMont, currentDay);
Atualizei, muito obrigado

2023-10-08 13:22 UTC, lguima requested changes
@MoisesMsa

2023-10-08 13:22 UTC, lguima commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(currentYear, currentMonth, currentDay);
Inicializar essa propriedade é redundante aqui, pois o `new Date()` já inicializa com a data atual por padrão.

```suggestion
```

2023-10-08 14:13 UTC, MoisesMsa commented on src/app/modules/components/date-picker-range/date-picker-range.component.ts
> +    this.maxDate = new Date(currentYear, currentMonth, currentDay);
@lguima atualizado

2023-10-08 20:37 UTC, lguima approved these changes
LGTM 🚀

2023-10-09 19:39 UTC, ogecece approved these changes
Shou!

![_](https://media.tenor.com/aZd_Kr2Z9J4AAAAC/excellent-great.gif)

2023-10-09 20:00 UTC, merged