Adiciona post-48
okfn-brasil/querido-diario-frontend pull request #227
Opened 2023-11-10 14:19 UTC by rasrbk

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [x] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2023-11-10 15:48 UTC, ogecece requested changes
Alguns pontos de correção:

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><em><span style="font-weight: 400;">Em cerca de um m&ecirc;s o n&uacute;mero de munic&iacute;pios integrados foi duplicada, superando todas as expectativas&nbsp;</span></em></p>
Pode tirar tudo que é `span` e tudo que tem `style=...`?

Dois motivos:
1. No blog a gente usa o `p` pro texto e o `span` tá mapeado diferente do `p` na folha de estilos (`styles.sass` e `blog-post.component.sass` são as referências para o blog)
2. Usar estilo embutido dificulta a manutenção pois se quisermos aplicar uma mudança na folha de estilos (nesse caso de `font-weight`) pra que seja refletida em todos os posts do blog, os que tiverem estilo embutido não vão permitir essa mudança e teria que mudar na mão

Inclusive, no PR #192 comentei isso também e não deveria ter passado.

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<img src="https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-card.jpeg">
Esse card não é o que está com os espaçamentos corrigidos. Não usa mais ele, por favor.

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<img src="https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-card.jpeg">
E pra que não fique tão grande, pode exportar com uns 400px de largura que acho que fica bom o tamanho.

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><strong><em>[Confira lista das novas cidades no sininho no canto superior direito do <a href="https://queridodiario.ok.org.br/blog">site do Querido Di&aacute;rio</a>].&nbsp;</em></strong></p>
O link seria pra página inicial e não `/blog`
```suggestion
<p><strong><em>[Confira lista das novas cidades no sininho no canto superior direito do <a href="https://queridodiario.ok.org.br/" target="_blank">site do Querido Di&aacute;rio</a>].&nbsp;</em></strong></p>
```

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><span style="font-weight: 400;">A Hacktoberfest &eacute; um acontecimento aguardado o ano todo por projetos de c&oacute;digo aberto ao redor do mundo. Isso tamb&eacute;m ocorre com o Querido Di&aa
Todos os links precisam de `target="_blank"` para que sejam abertos em uma nova guia.

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><em><span style="font-weight: 400;">&nbsp;</span></em></p>
Pode remover essa linha? Está sem conteúdo

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><span style="font-weight: 400;">No geral, os feedbacks foram bastante positivos para a participa&ccedil;&atilde;o do Querido Di&aacute;rio na Hacktoberfest deste ano, em especial com rela&ccedil;&
`&nbsp;` no final da linha como esse é espaço em branco que pode ser removido
```suggestion
<p><span style="font-weight: 400;">No geral, os feedbacks foram bastante positivos para a participa&ccedil;&atilde;o do Querido Di&aacute;rio na Hacktoberfest deste ano, em especial com rela&ccedil;&atilde;o ao engajamento das pessoas nos eventos promovidos e movimenta&ccedil;&atilde;o no servidor. Para Juliana Trevine, a forma&ccedil;&atilde;o de grupos de trabalho voltados para &aacute;reas espec&iacute;ficas do projeto pode ter ajudado. Tr&ecirc;s </span><a href="https://queridodiario.ok.org.br/blog/post/41"><span style="font-weight: 400;">GTs iniciaram atividades</span></a><span style="font-weight: 400;"> em agosto deste ano e seguem at&eacute; o final deste m&ecirc;s. A expectativa &eacute; que essa din&acirc;mica continue fazendo parte da comunidade daqui para frente.</span></p>
```

2023-11-10 15:48 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p><strong>Eventos</strong></p>
A formatação ficaria melhor fazendo uso de cabeçalhos `h1`, `h2` e `h3`. Como tá tudo sendo diferenciado por negrito ou não-negrito não dá pra diferenciar tanto e fica até confusa a leitura de trechos como esse:

![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/42153733-b555-4a4b-a287-9bfe2f3efde6)

2023-11-10 16:01 UTC, trevineju requested changes

2023-11-10 16:01 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><em><span style="font-weight: 400;">Em cerca de um m&ecirc;s o n&uacute;mero de munic&iacute;pios integrados foi duplicada, superando todas as expectativas&nbsp;</span></em></p>
Vinhamos adotando a adição de uma linha para fazer quebra entre a linha fina e o texto. 

Exemplo: ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/44185775/6b8c2631-d0aa-4cd4-872d-2f6684169a62)

Precisa adicionar aqui também. Para isso, basta adicionar a tag `<hr>` 

https://www.w3schools.com/tags/tag_hr.asp

2023-11-13 18:29 UTC, rasrbk commented on src/assets/pages/blogposts/post-48.html
> +<p><strong>Eventos</strong></p>
nesse caso, esses títulos seriam qual tamanho? qual o critério pra escolha entre h1, h2 ou h3?

2023-11-13 18:45 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><strong>Eventos</strong></p>
pode ser visual mesmo, @rasrbk. Tem que ser um tamanho menor que o título da postagem para não competir com a hierarquia visual do conteúdo. Fora isso, pode ser a que parecer do melhor tamanho/destaque. Tenta elas e vê a que parecer melhor. 

De referência, aqui [nesse post](https://queridodiario.ok.org.br/blog/post/43), usei h2 em "participe..." e h3 em "raspadores", "site", "documentação". Não lembro pq não usei h1.

2023-11-13 20:31 UTC, rasrbk commented on src/assets/pages/blogposts/post-48.html
> +<p><strong>Eventos</strong></p>
pelo que tenho visto em postagens antigas no blog do QD e outras referências para html é melhor seguir a hierarquia de h1 - título, h2 - intertítulo e assim sucessivamente. pelo que vi, não temos usado h1 no corpo do texto.

2023-11-13 20:34 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><span style="font-weight: 400;">Pedro Guimar&atilde;es, tamb&eacute;m da equipe de Inova&ccedil;&atilde;o C&iacute;vica, destacou a import&acirc;ncia deste momento: &ldquo;</span><em><span style="
é o formato oficial da folha de estilo do projeto. Adiciona a correção e a gente vê como fica. 

Se alguma mudança precisar ser feita, depois o estilo pode ser adaptado.

2023-11-14 13:09 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><em><span style="font-weight: 400;">Em cerca de um m&ecirc;s o n&uacute;mero de munic&iacute;pios integrados foi duplicada, superando todas as expectativas&nbsp;</span></em></p>
atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 13:10 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<img src="https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-card.jpeg">
aparentemente, foi decidido pela remoção em atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 13:13 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><strong><em>[Confira lista das novas cidades no sininho no canto superior direito do <a href="https://queridodiario.ok.org.br/blog">site do Querido Di&aacute;rio</a>].&nbsp;</em></strong></p>
foi corrigido em atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 13:14 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><span style="font-weight: 400;">A Hacktoberfest &eacute; um acontecimento aguardado o ano todo por projetos de c&oacute;digo aberto ao redor do mundo. Isso tamb&eacute;m ocorre com o Querido Di&aa
foi atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 13:15 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><em><span style="font-weight: 400;">&nbsp;</span></em></p>
foi atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 13:17 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><strong>Eventos</strong></p>
foi atendido em https://github.com/okfn-brasil/querido-diario-frontend/pull/227/commits/decc4930efe70c0e2fe2351859d94ba930afa64c

2023-11-14 14:15 UTC, trevineju requested changes

2023-11-14 14:15 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><span style="font-weight: 400;">Pedro Guimar&atilde;es, tamb&eacute;m da equipe de Inova&ccedil;&atilde;o C&iacute;vica, destacou a import&acirc;ncia deste momento: &ldquo;</span><em><span style="
Da leva anterior, ficou faltando esse ajuste @rasrbk. Agora, passou a usar `<em>` para todas as citações, e não são tags adequadas. As tags padrão de citações são estas: https://www.w3schools.com/html/html_quotation_elements.asp

E, como havia dito, aqui no projeto temos uma específica, a `quote-paragraph` que deve ser usada pq é estilização oficial do repositório. Nos parágrafos em que a citação é a maior parte do texto, aplique. Nos casos em que a citação se mistura no parágrafo, usa o `<q>` e aí avaliamos como fica.

2023-11-14 21:01 UTC, ogecece requested changes

2023-11-14 21:01 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p>Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>
```suggestion
<p><quote-paragraph>"Essa foi a Hacktoberfest com maior engajamento da comunidade que o Querido Diário já teve! A cobertura de municípios quase dobrou em um mês. Nos preparamos para um grande evento, mas os resultados superaram todas as expectativas!"</quote-paragraph> comemora Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>
```

2023-11-14 22:46 UTC, ogecece commented on src/assets/pages/blogposts/post-48.html
> +<p>Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>
Ainda precisa corrigir no `blog.json`

2023-11-16 18:06 UTC, trevineju requested changes

2023-11-16 18:06 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p><i>Em cerca de um mês o número de municípios integrados foi duplicado, superando todas as expectativas. </i></p>
```suggestion
<p><em>Em cerca de um mês o número de municípios integrados foi duplicado, superando todas as expectativas. </em></p>
```

De todos os `<em>` que tinha antes, este estava certo. Aqui, enquanto linha fina, realmente é uma "enfase" e não um mero "itálico"

2023-11-16 18:06 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p>No primeiro sábado do mês (7 de outubro), foi realizado um workshop de abertura da Hacktoberfest. Na ocasião, Juliana Trevine, do programa de Inovação Cívica da OKBR, apresentou o repositório de r
```suggestion
<p>No primeiro sábado do mês (7 de outubro), foi realizado um workshop de abertura da Hacktoberfest. Na ocasião, Juliana Trevine, do programa de Inovação Cívica da OKBR, apresentou o repositório de raspadores do Querido Diário e junto a comunidade, combinou tarefas (<i>issues</i>) que cada pessoa manifestou interesse em fazer, com diferentes níveis de dificuldade. A atividade de recepção foi buscando dar oportunidade para quem estava chegando no servidor a se familiarizar com essa frente do projeto de forma guiada e tirar dúvidas gerais.</p>
```

2023-11-16 18:06 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p class="quote-paragraph"><q>"Essa foi a Hacktoberfest com maior engajamento da comunidade que o Querido Diário já teve! A cobertura de municípios quase dobrou em um mês. Nos preparamos para um gran
```suggestion
<p class="quote-paragraph"><q>Essa foi a Hacktoberfest com maior engajamento da comunidade que o Querido Diário já teve! A cobertura de municípios quase dobrou em um mês. Nos preparamos para um grande evento, mas os resultados superaram todas as expectativas!</q> celebra Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>
```
Tinha um `<p>` extra aqui

2023-11-16 18:06 UTC, trevineju commented on src/assets/pages/blog.json
> +      "content": "<p><i>Em cerca de um mês o número de municípios integrados foi duplicado, superando todas as expectativas. </i></p><hr /><p>A Hacktoberfest é um acontecimento aguardado o ano todo p
```suggestion
      "content": "<p><em>Em cerca de um mês o número de municípios integrados foi duplicado, superando todas as expectativas. </em></p><hr /><p>A Hacktoberfest é um acontecimento aguardado o ano todo por projetos de código aberto ao redor do mundo. Isso também ocorre com o Querido Diário, que já começa o mês de setembro se preparando para a festa. O evento mundial incentiva contribuições a projetos de código aberto durante o mês de outubro e isso se reflete no engajamento da nossa comunidade.</p><p>Este ano, o QD recebeu muitas contribuições e novas pessoas ingressaram no servidor da Open Knowledge Brasil (OKBR) no Discord, onde eventos virtuais foram organizados para auxiliar quem estava começando e/ou contribuindo com o projeto. <strong>Confira agora um balanço das iniciativas e impactos da festa: </strong></p><h2>Eventos</h2><h3>Abertura</h3><p>No primeiro sábado do mês (7 de outubro), foi realizado um workshop de abertura da Hacktoberfest. Na ocasião, Juliana Trevine, do programa de Inovação Cívica da OKBR, apresentou o repositório de raspadores do Querido Diário e junto a comunidade, combinou tarefas (<i>issues</i>) que cada pessoa manifestou interesse em fazer, com diferentes níveis de dificuldade. A atividade de recepção foi buscando dar oportunidade para quem estava chegando no servidor a se familiarizar com essa frente do projeto de forma guiada e tirar dúvidas gerais.</p><h3>Sprint Querido Diário em parceria com a BOSS</h3><p>Uma das novidades foi a parceria com o programa Big Open Source Sibling (<a href='https://www.instagram.com/open.source.sibling/' target='_blank'>BOSS</a>), focado em engajar grupos sub-representados na tecnologia para contribuir para projetos de código aberto. Junto com a iniciativa, foi realizada, pela primeira vez, uma sprint focada em melhorias no frontend do Querido Diário. </p><p>O momento teve três encontros síncronos: 18 e 20 de outubro, no servidor da OKBR. E no dia 22 de outubro, em modelo híbrido, com a equipe da BOSS presencialmente no Calango Hacker Club, em Brasília-DF, e a comunidade do Querido Diário online no Discord.</p><img src='https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-print.jpeg'><h3>Palestras</h3><p>Juliana Trevine também participou de outros eventos, um deles promovido pela comunidade GitHub São Paulo e outro pelo Diretório Acadêmico de Sistemas de Informação (DASI-USP), nos quais ela representou a comunidade do Querido Diário, apresentando o projeto.</p><h2>Números</h2><p>O repositório principal, <a href='https://github.com/okfn-brasil/querido-diario' target='_blank'>querido-diario</a>, é onde estão as informações sobre os raspadores responsáveis pela coleta de diários oficiais em sites de prefeituras alimentando as informações disponibilizadas pelo QD. Em anos anteriores, este repositório recebia quase toda a atenção da comunidade.</p><p>Porém, outra novidade este ano foi a maior atenção dada aos repositórios do Querido Diário que anteriormente não costumavam receber tantas contribuições no âmbito da Hacktoberfest. É o caso do <a href='https://github.com/okfn-brasil/querido-diario-frontend' target='_blank'>querido-diario-frontend</a>, que guarda o código do site, e também do <a href='https://github.com/okfn-brasil/querido-diario-comunidade' target='_blank'>querido-diario-comunidade</a>, onde fica concentrada toda a documentação geral e discussões transversais aos vários repositórios do projeto e sua comunidade.</p><img src='https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-grafico-2.png'><p>Além dos <i>pull requests</i> (PRs), os repositórios do QD também foram movimentados com a criação de Issues, que representam demandas específicas que as pessoas contribuidoras notam como necessárias para melhorar o projeto.</p><h3>Segunda centena de municípios</h3><p>Por conta das contribuições no desenvolvimento de raspadores, uma grande conquista da participação na Hacktoberfest deste ano foi a <strong>integração de mais de 100 cidades ao Querido Diário.</strong> Como comparação, nesse mesmo período no ano passado, o projeto tinha cerca de 50 cidades e contribuições para cerca de 40 novas cidades foram feitas em outubro, das quais 9 foram integradas ao longo do mesmo mês. Neste ano, iniciamos a Hacktoberfest com 118 municípios cadastrados na plataforma e chegamos ao dia 31 com 231!</p><p><i><strong>[Confira lista das novas cidades no sininho no canto superior direito].</strong></i></p><p class='quote-paragraph'><q>Para um projeto que levou dois anos para atingir 100 municípios e tem o ousado objetivo de cobrir todo o país, ter conseguido adicionar 113 em apenas um mês é como realizar um experimento que deu super certo. Nós nos beneficiamos do interesse por contribuição que a Hacktoberfest impulsiona, claro, mas que só pode ser tão bem aproveitado graças às decisões de projeto que consolidaram o Querido Diário até aqui. Aos poucos, vamos virando a chave da história do QD para crescer cada vez mais.</q> destaca Juliana Trevine, analista de desenvolvimento em inovação cívica na OKBR.</p><img src='https://querido-diario-static.nyc3.cdn.digitaloceanspaces.com/post0048/post-48-grafico-1.png'><h2>Aprendizados</h2><p>Devido ao foco em novos repositórios para recebimento de contribuições, alguns aprendizados aconteceram na prática e devem ser levados em consideração na Hacktoberfest de 2024.</p><h3>Frontend</h3><p>Lucas Guimarães, mantenedor do repositório querido-diario-frontend, destacou que nesse repositório será importante ficar atento não apenas para a quantidade de contribuições, mas também para a qualidade do que está sendo desenvolvido:</p><p class='quote-paragraph'><q>Houve novas adições ao produto vindas de sugestões de novas funcionalidades feitas por colaboradores recém-chegados ao projeto, sem que necessariamente as sugestões propostas estivessem alinhadas com a gestão e fizessem sentido como um todo. No ano que vem vamos precisar utilizar melhor as labels para especificar as características da issue e tentar estabelecer um mecanismo de validar as entradas com os mantenedores, aceitando-as ou não</q> reforça Lucas Guimarães. </p><p>Para lidar com essa questão, Pedro Guimarães reforça que <q>Ano que vamos ter uma melhor gestão prévia do repositório, com preparação e criação de issues e maior dedicação na aplicação da label 'good first issue', que indica as issues mais fáceis</q>, explica.</p><h2>Feedbacks da comunidade</h2><p>No geral, os feedbacks foram bastante positivos para a participação do Querido Diário na Hacktoberfest deste ano, em especial com relação ao engajamento das pessoas nos eventos promovidos e movimentação no servidor. Para Juliana Trevine, a formação de <a href='https://queridodiario.ok.org.br/blog/post/41' target='_blank'>grupos de trabalho</a> voltados para áreas específicas do projeto pode ter ajudado. Três GTs iniciaram atividades em agosto deste ano e seguem até o final deste mês. A expectativa é que essa dinâmica continue fazendo parte da comunidade daqui para frente.</p><p>Muita gente nova também ingressou na comunidade durante a Hacktoberfest. Somente entre os dias 3 e 30 de outubro, 78 novas pessoas entraram no <a href='https://go.ok.org.br/discord' target='_blank'>servidor da OKBR</a> no Discord!</p><p class='quote-paragraph'><q>Essa foi a Hacktoberfest com maior engajamento da comunidade que o Querido Diário já teve! A cobertura de municípios quase dobrou em um mês. Nos preparamos para um grande evento, mas os resultados superaram todas as expectativas!</q> celebra Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>",
```

2023-11-16 18:10 UTC, trevineju commented on src/assets/pages/blogposts/post-48.html
> +<p>Giulio Carvalho, coordenador de inovação cívica na OKBR.</p>
o jeito de usar o `quote-paragraph` é: `<p class='quote-paragraph'><q>` 
Mas validei que nos commits recentes está aplicado certo tanto no `.html` quanto em `.json`

2023-11-16 19:13 UTC, trevineju approved these changes

2023-11-16 19:13 UTC, merged