Implementação de funcionalidades de download de excertos selecionados na página geral e no Portal Educação
okfn-brasil/querido-diario-frontend pull request #262
Opened 2024-04-19 18:51 UTC by csafurtado

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [X] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [X] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [X] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
Até o momento, sem issues relacionadas.

## Validação

* [X] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [X] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

* <h4>Portal Geral</h4>
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/77639735/a5b11257-78c2-4d2a-b41d-1f01abc234c3)
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/77639735/399d0c04-1b0c-4edb-9186-bd14bba07549)

* <h4>Portal Educação</h4>
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/77639735/73ea11f0-7c28-45d9-960f-c251c5a2c005)
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/77639735/710c1fc6-6b1d-4386-bad4-b5a496225997)

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-04-23 19:25 UTC, ogecece requested changes
Legal, tamo chegando lá!

Vou elencar aqui um problema que está impossibilitando a revisão de código e depois alguns problemas de interface que já consigo revisar.

A história dos commits está confusa como a `main` foi mesclada à branch de funcionalidade nos commits 88b8205, bb1cb11 e 619390e . Poderiam ajustar para que apenas os commits relacionados a esta funcionalidade possam ser revisados? Desse jeito tem muita coisa extra, então não consigo fazer a revisão de código. Se precisarem de ajuda podemos agendar uma chamada.

- [ ] 1. Botão de "Baixar selecionados" só aparece quando logado no QD-Edu e deveria aparecer sempre
    <details><summary>Prints</summary>
           
    | Sem login | Com login |
    |---|---|
    | ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/7e718e50-827b-4cc3-9088-667fd45a12d1) | ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/50087407-2a46-456d-aefd-e3e0b033d34d) |
    </details>
- [ ] 2. Elementos deveriam ter efeito ao clicar
    <details><summary>Prints</summary>
           
    ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/678cad59-58e3-4a23-9669-af72d5334e0b)
    </details>
- [x] 3. Elementos deveriam indicar que são clicáveis (mãozinha)
    <details><summary>Prints</summary>
           
    - [x] 3.1. 
    
        ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/cd35da9c-efb4-430b-9ccf-4ff717ee6dbd)
    
    - [x] 3.2. 
    
        ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/6b6c6fd0-ba24-45c7-a6a7-2b97b06cce48)
    </details>
- [x] 4. Não precisamos desse alerta. Basta o botão não ser clicável sem excertos selecionados 
    <details><summary>Prints</summary>
           
    ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/1cdda430-14eb-4d3d-97d3-b67044f188c5)
    </details>
- [x] 5. Quando propuseram o alinhamento à esquerda do "Selecionar todos" no QD-Edu no protótipo imaginei que iria refletir aqui também. Também sugiro mudar o texto para "Selecionar todos" para padronizar 
    <details><summary>Prints</summary>
           
    ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/1a46afcc-17d7-4096-9feb-c2d785d20c07)
    </details>
- [x] 6. Elementos estão com tons diferentes de laranja. Ambos deveriam ser #FF8200
    <details><summary>Prints</summary>
           
    - [x] 6.1. 
    
        ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/e9c35563-f513-45f1-b973-f5c48258c781)
    
    - [x] 6.2. 
    
        ![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/871282ae-edc2-419a-b6cd-a0fd3900a653)

    </details>
- [ ] 7. Alguns problemas na contagem de excertos selecionados. Fiz uma gravação de tela (perdão pela qualidade mas o github só permite vídeos de até 10MB) pra pegar todos os que consegui achar
    <details><summary>Gravações de tela</summary>
           
    - [ ] 7.1. 
    
        https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/298bb137-744e-4fef-9666-4cadca2fd648
    
    - [x] 7.2. 
      
        https://github.com/okfn-brasil/querido-diario-frontend/assets/26327506/dd2b59ed-19e0-42bd-8ff3-8640f3504f0e

    </details>

2024-05-06 20:33 UTC, csafurtado commented
@ogecece as modificações solicitadas foram realizadas!

2024-05-08 12:55 UTC, ogecece reviewed
Todos os pontos dos meus últimos comentários exceto os itens 1, 2 e 7 foram corrigidos! (já marquei lá)

Itens 1 e 2 são referentes ao QD-Edu e não tiveram alteração e o item 7 foi corrigido no QD-Edu mas não na busca principal.

2024-05-09 21:29 UTC, ogecece commented
Validei as outras funcionalidades. Só aguardando os commits serem substituídos para poder iniciar a revisão de código!

2024-05-10 11:25 UTC, wildemberg-sales commented
Foi efetuado a correção dos problemas apontados, e corrigido o problema com as ramificações, atualmente a árvore de commits está linear e sem duplicações

2024-05-10 16:11 UTC, ogecece requested changes
Primeiro, desculpem pelo número de pedidos de alteração. Como a busca do QD e a do QD-Edu tem suas diferenças, tentei encontrar maneiras de tornar pelo menos as nomenclaturas consistentes e fui apontando onde conseguia. Posso ter deixado coisas passarem e já peço desculpas se uma próxima revisão de código tenha pedidos que deixei passar nessa primeira.

Segunda coisa é que agora que consegui fazer o review de código tenho um pedido. Assim que a gente completar as modificações e disser que o código está aprovado, podemos fazer squash em todos os commits de "correção"? Só pra manter os commits que realmente estão adicionando alguma funcionalidade ou implementando uma mudança de estilo.

2024-05-10 16:11 UTC, ogecece commented on src/app/modules/pages/search/search.component.sass
> +  font-weight: 500
Isso não deveria estar dentro do item da linha 85?

2024-05-10 16:11 UTC, ogecece commented on src/app/modules/pages/search/search.component.ts
> +  selectExcerpts(territory_name: string,
`selectSearchResults` ou algo do tipo

2024-05-10 16:11 UTC, ogecece commented on src/app/modules/pages/search/search.component.ts
> +    let indexOfVal = listGazetteCSV.findIndex((gazette) => gazette.id == val.id)
`val` seria `csvItem` e `indexOfVal` seria `csvItemId`?

2024-05-10 16:11 UTC, ogecece commented on src/app/modules/pages/search/search.component.ts
> +  isGazzeteSelected(gazetteId: string) {
```suggestion
  isSearchResultSelected(gazetteId: string) {
```

2024-05-10 16:11 UTC, ogecece commented on src/app/modules/pages/search/search.component.ts
> +  isAllSelected() {
```suggestion
  isCheckboxCheckAllSelected() {
```

2024-05-13 13:05 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/search/search.component.html
> +          <!--terniar-->
Removido em 838d63a

2024-05-13 13:06 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/area-education/search/item/item.component.ts
> +
Removido em 838d63a

2024-05-13 13:06 UTC, ArthurFerreiraRodrigues commented on src/app/modules/components/search-form/search-form.component.sass
> +
Removido em 838d63a

2024-05-13 15:27 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/area-education/search/search.component.html
> +              <input type="checkbox" name="checkbox-gazette" [id]="item.url+currPage+i" (change)="addValuesCsv(item.territory_name, item.state_code, item.excerpt, item.date, item.edition, item.is_ext
Neste caso, o ID deve variar junto de acordo com o índice dele na página, dessa forma, em conjunto com o número da página, é possível criar um id único para cada item do resultado. Isso foi necessário pois em alguns casos pesquisas trazem dois ou mais itens iguais.

2024-05-13 15:28 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/area-education/search/search.component.ts
> +  checkSelectAll(val:boolean){
Correto.

2024-05-13 15:45 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/search/search.component.ts
> +    listGazetteCSV.map((val)=>{
Não utilizar nomes genéricos.

2024-05-13 15:46 UTC, ArthurFerreiraRodrigues commented on src/app/modules/pages/search/search.component.ts
> +    let checkFather = document.querySelector('#father') as HTMLInputElement
Remover qualquer referência a "father". Utilizar algo que remeta a selecionar todos, como `checkboxSelectAll`

2024-05-13 16:28 UTC, ArthurFerreiraRodrigues commented
@ogecece Correções e refatorações aplicadas. Solicito sua revisão.

2024-05-15 13:46 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.sass
> +
@ogecece poderia explicar de onde foi tirado esse print dos subtemas? Pois no site mesmo do QD em diferentes navegadores nós o encontramos com um estilo diferente (na imagem a seguir) 
![image](https://github.com/okfn-brasil/querido-diario-frontend/assets/77639735/cb30c9e0-0b9e-4b7a-ae43-35dcdc3f4f55)

2024-05-28 13:13 UTC, ogecece commented on src/app/modules/pages/area-education/search/search.component.sass
> +
@csafurtado esses prints são com a modificação que sugeri ali no comentário

2024-05-28 13:18 UTC, wildemberg-sales commented on src/app/modules/pages/area-education/search/search.component.sass
> +
@ogecece então só para confirmar, devemos implementar isso em todos os checkbox's da página correto?

2024-05-28 14:08 UTC, ogecece commented on src/app/modules/pages/area-education/search/search.component.sass
> +
Isso, todos os checkboxes passarem a usar essa implementação que já existe, porém com a correção sugerida

2024-05-28 14:15 UTC, ogecece requested changes
Mais um comentário: podemos manter o valor no CSV como vazio caso o campo não tenha conteúdo? `numero_edicao` está aparecendo como `null`, por exemplo.

E também encontrei mais um problema:

2024-05-28 20:20 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.sass
> +
Aah sim, entendi! Irei então aplicar essas mudanças e reutilizar esse checkbox

2024-06-04 19:32 UTC, csafurtado commented on src/app/modules/pages/search/search.component.ts
> +    };
Resolvido!

2024-06-04 19:32 UTC, csafurtado commented on src/app/modules/pages/search/search.component.ts
> +          'URL_PDF_Original',
Resolvido!

2024-06-04 19:32 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.ts
> +          'Entidades',
Resolvido!

2024-06-04 19:33 UTC, csafurtado commented on src/app/interfaces/download-csv.ts
> +  numero_edicao?: string;
Resolvido!

2024-06-04 19:33 UTC, csafurtado commented on src/app/modules/pages/search/search.component.html
> +              Selecionados{{getQntSelected}}</span>
Modificado!

2024-06-04 19:34 UTC, csafurtado commented
As modificações solicitadas foram aplicadas @ogecece! Poderia verificá-las por gentileza?

2024-06-05 15:48 UTC, ogecece requested changes
Encontrei dois probleminhas e o resto tá tudo 100%. Depois disso já podem fazer os squash o/

2024-06-05 15:48 UTC, ogecece commented on src/app/modules/pages/search/search.component.ts
> +    };
Acredito que esteja faltando a extração do `edition` -> `numero_edicao` aqui, como há no QD-Edu

2024-06-05 15:48 UTC, ogecece commented on src/app/modules/pages/area-education/search/search.component.ts
> +        envolvidos: selectedResult.envolvidos,
Acabei de reparar que os resultados com mais de um subtema ou envolvidos quebra esses campos em mais de uma coluna por estarem separados por vírgula. Poderiam separar os itens desses campos por ponto e vírgula pra serem considerados apenas uma coluna?

2024-06-05 16:26 UTC, csafurtado commented on src/app/modules/pages/search/search.component.ts
> +    };
Resolvido!

2024-06-05 16:26 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.ts
> +        envolvidos: selectedResult.envolvidos,
Colocado como ponto e vírgula agora!

2024-06-05 19:04 UTC, ogecece commented on src/app/modules/pages/area-education/search/search.component.ts
> +        envolvidos: selectedResult.envolvidos,
@csafurtado a ideia seria manter o separador de colunas como vírgula e separar os itens apenas desses dois campos por ponto-e-vírgula. Ficou o contrário hehehe

2024-06-05 19:26 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.ts
> +        envolvidos: selectedResult.envolvidos,
Aaaa tá, ok! Vou corrigir kkkkk

2024-06-05 20:12 UTC, csafurtado commented on src/app/modules/pages/area-education/search/search.component.ts
> +        envolvidos: selectedResult.envolvidos,
Prontinho!

2024-06-05 20:35 UTC, ogecece approved these changes
Valeu! PR APROVADO!

2024-06-05 20:36 UTC, ogecece commented
Pode fazer os squashs nos commits de correção

2024-06-05 20:52 UTC, csafurtado commented
@ogecece o squash no caso você mesmo pode fazer na própria opção de dar o merge aqui. Seria esse squash que vc se refere?

2024-06-05 20:59 UTC, ogecece commented
Esse daqui seria pra reduzir todos os commits do PR a um commit apenas. O que eu queria é que vocês usassem o rebase interativo para fazer squash apenas nos commits de correção e manter os commits de funcionalidade

2024-06-05 21:02 UTC, csafurtado commented
Aah sim entendi! Faremos então!

2024-06-07 13:38 UTC, ogecece commented
Squash aprovado!

2024-06-07 13:39 UTC, merged