(WIP ) - Página de Pedido de Análise Customizada
okfn-brasil/querido-diario-frontend pull request #263
Opened 2024-04-22 05:22 UTC by EdimarioJr

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [ ] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [ ] Eu li e segui o [Código de Conduta](https://github.com/okfn-brasil/querido-diario-comunidade/blob/main/.github/CODE_OF_CONDUCT.md).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
Issues que são relacionadas a esta Pull Request.

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-04-23 14:14 UTC, ogecece commented
Tá ficando legal @EdimarioJr! Se precisar de qualquer apoio só falar

2024-04-23 21:37 UTC, EdimarioJr commented
> Tá ficando legal @EdimarioJr! Se precisar de qualquer apoio só falar

Obrigado @ogecece ! Não tô conseguindo dar a vazão que queria nessa task por motivos de correria no trabalho, mas tá indo!

2024-04-29 21:38 UTC, ogecece reviewed
@EdimarioJr tá ficando :100: 

Como vc falou, no Discord, que a parte do frontend está pronta, vou revisar essa parte. Se já planejava essas correções, só avisar.

1. Ao clicar em qualquer "Subtema", o item some e não volta mais
2. A lista de "Envolvidos" está vazia

2024-04-29 21:38 UTC, ogecece commented on src/app/modules/pages/area-education/request-analysis-form/request-analysis-form.component.html
> +                compreender a partir da análise
```suggestion
                Explique os detalhes do tipo de informação que deseja
                compreender a partir da análise
```

2024-07-25 22:04 UTC, ogecece requested changes
@EdimarioJr os testes que realizei passaram bem! Coloquei algumas melhorias que senti que precisamos fazer. Mas tá muito próximo de finalizar

2024-07-25 22:04 UTC, ogecece commented on src/app/modules/pages/area-education/request-analysis-form/request-analysis-form.component.ts
> +      ],
Colocar um asterisco no nome dos campos obrigatórios também seria interessante

2024-07-25 22:04 UTC, ogecece commented on src/app/modules/pages/area-education/request-analysis-form/request-analysis-form.component.ts
> +              'Fechar'
```suggestion
              'Erro ao enviar pedido. Por favor, tente mais tarde.',
              'Fechar'
```

2024-07-30 21:01 UTC, ogecece approved these changes
@EdimarioJr dei uma reorganizada (pensei que os asteriscos ficariam bem, mas não curti muito, por exemplo) e traduzi os territory_id pro nome do município + state_code por extenso.

Vou mesclar \o/

2024-07-30 21:14 UTC, merged