Implementação da página de download dos arquivos agregados por ano e município/estado
okfn-brasil/querido-diario-frontend pull request #286
Opened 2024-08-12 19:54 UTC by wildemberg-sales

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/codigo-de-conduta.html).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [x] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [x] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-08-14 22:29 UTC, ogecece requested changes
Aqui no frontend tá 95% pronto. Muito bom!

Como não consegui fazer funcionar em código, vou deixar um comentário aqui mesmo. Podemos apresentar o nível de abertura embaixo do nome de cada município durante a busca (como é na busca principal do QD)? Ou então deixar disponíveis apenas os de nível 3 como é no QD-Edu? Atualmente, qualquer município está disponível ali, sem nenhum feedback de qual estaria disponível.

2024-08-14 22:29 UTC, ogecece commented on src/app/modules/pages/aggregate/filters/state-filter/aggregate-state-filter.component.html
> +    </div> -->
Pode remover? Ou, como é um spinner de loading, ativar?

2024-08-14 22:30 UTC, ogecece requested changes

2024-08-14 22:30 UTC, ogecece commented on src/app/modules/components/aggregate-data/aggregate-data.component.html
> +          <p>A tabela apresenta informações sobre o arquivo xml a ser baixado.</p>
```suggestion
          <p>A tabela apresenta informações sobre o arquivo XML a ser baixado.</p>
```

2024-08-14 22:33 UTC, ogecece requested changes

2024-08-14 22:33 UTC, ogecece commented on src/app/modules/pages/aggregate-search/aggregate-search.component.html
> +          disponível para download!
Esse texto aparece tanto na página de resultados de UF quanto de município.
```suggestion
          Abaixo, estão os resultados encontrados na localidade informada
          informado. Os dados estão organizados de maneira compactada e
          disponível para download!
```

2024-08-15 14:12 UTC, esteerlino commented
Feitas as alterações solicitadas!

2024-08-15 14:56 UTC, ogecece commented on src/app/modules/components/aggregate-data/aggregate-data.component.html
> +          <p>A tabela apresenta informações sobre o arquivo xml a ser baixado.</p>
Não prestei atenção suficiente aqui antes. As informações são sobre o arquivo ZIP. Na real, acho melhor omitir a info sobre o tipo do arquivo aqui. Vou fazer outro comentário em seguida @esteerlino

2024-08-15 15:06 UTC, ogecece requested changes

2024-08-15 15:06 UTC, ogecece commented on src/app/modules/components/aggregate-data/aggregate-data.component.html
> +          <p>A tabela apresenta informações sobre o arquivo XML a ser baixado.</p>
Como comentei antes, aqui seria o ZIP então acho que faz mais sentido omitir o tipo do arquivo mesmo.
```suggestion
          <p>A tabela apresenta informações sobre o arquivo a ser baixado.</p>
```

2024-08-15 16:14 UTC, esteerlino commented
@ogecece Corrigido!

2024-08-15 17:43 UTC, ogecece approved these changes
Massa! E valeu por ter identificado e removido as URLs de desenvolvimento local @esteerlino !

2024-08-19 12:52 UTC, merged