Correção da exibição do dropdown de cidades
okfn-brasil/querido-diario-frontend pull request #299
Opened 2024-09-23 03:42 UTC by MoisesMsa

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x ] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x ] Eu li e segui o [Código de Conduta](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/codigo-de-conduta.html).

## Tipo de alteração

* [x ] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
#259 

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-09-23 18:18 UTC, lguima requested changes
fala @MoisesMsa, esse bug vc foi ninja pra achar haha

só que eu testei o preview no Chrome (129.0.6668.58) e o comportamento tá igual de produção

vc testou em qual navegador?

2024-09-23 19:30 UTC, MoisesMsa commented
@lguima testei a preview no Firefox e no Chrome, precisei de alguns passos extras para reproduzir o problema (se não entendi errado):

1. Preenche o campo de pesquisa
2. Digita o nome da cidade e apaga o texto

O dropdown para de ser exibido.

Tem um problema relacionado ao hover do cursor, notei agora, ao remover o cursor de cima do dropdown ele some, com a correção dessa PR sempre que o usuário volta a digitar as sugestões voltam a aparecer, em prod o dropdown não abre.

Posso corrigir esse comportamento do hover nessa PR também pra não precisar abrir outra issue.

2024-09-24 17:43 UTC, lguima commented
nossa @MoisesMsa, foi mal, eu recebi a notificação do bug que vc abriu, eu achei que essa PR corrigia ele, agora que vi que tá relacionada com outra issue

e acabei de reparar esse comportamento que vc falou tb, acho que vale a gente atualizar a issue pra cobrir esse cenário e fazer um fix só, pq pode ser que pra corrigir esse comportamento precise mudar o código que vc tá incluindo

tudo bem seguir assim?

2024-09-24 19:29 UTC, MoisesMsa commented
@lguima tranquilo 
Sim, podemos seguir assim

2024-09-28 21:16 UTC, MoisesMsa commented
@lguima atualizei a PR. Só mais uma observação fiz um pequeno ajuste para não exibir o placeholder quando tem cidades selecionadas:

![Screenshot from 2024-09-28 18-14-15](https://github.com/user-attachments/assets/4fb4f799-d67b-4e70-a4f5-c4ad229c567d)

![Screenshot from 2024-09-28 18-14-59](https://github.com/user-attachments/assets/0ab45735-6bb7-44b8-9f0e-1c8bcf4270c3)

2024-10-02 16:57 UTC, lguima approved these changes
boa, @MoisesMsa! valeu! :raised_hands:

2024-10-02 17:51 UTC, merged