Adiciona preview para o site
okfn-brasil/querido-diario-frontend pull request #313
Opened 2024-10-22 15:48 UTC by trevineju

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/codigo-de-conduta.html).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [x] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
Não resolve a issue #303, mas adiciona uma solução temporária

## Validação

* [x] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [x] Validei o Layout responsivo (desktop/mobile) após a implementação
* [x] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
![image](https://github.com/user-attachments/assets/a236f4de-0bd9-454c-baa9-a6fc86a382f2)

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-10-22 16:10 UTC, trevineju commented
@lguima, vc poderia dar uma revisão aqui? o `app.component.html` é o lugar certo de se adicionar as tags? 
como estavamos falando na issue, a ideia no momento seria uma solução só pro site todo.

testei com https://www.opengraph.xyz/url/https%3A%2F%2Fdeploy-preview-313--querido-diario-plataforma.netlify.app%2F e parece ter funcionar, mas não tenho certeza se o deploy-preview é o jeito certo de se testar isso.

2025-01-26 23:54 UTC, lguima requested changes
oi, @trevineju! nossa, só vi agr essa PR, desculpa!

2025-01-26 23:54 UTC, lguima commented on src/app/app.component.html
> +<meta itemprop="name" content="Querido Diario"/>
```suggestion
<meta itemprop="name" content="Querido Diário"/>
```

2025-01-26 23:57 UTC, lguima commented
@trevineju sobre o local para adicionar, seguindo a ideia de ter uma única imagem/descrição pra todas páginas, é no `app.component.html` msm

o `metaService` serve pro caso da gente querer mudar o conteúdo das meta tags em cada página

2025-01-29 17:19 UTC, trevineju commented
> o `metaService` serve pro caso da gente querer mudar o conteúdo das meta tags em cada página

ah, entendi!! 

então, essa PR é só isso, mesmo?

2025-01-30 12:19 UTC, lguima approved these changes
@trevineju é pra ser sim :rocket:

2025-01-31 20:12 UTC, merged

2025-01-31 23:15 UTC, lguima commented
@trevineju acho que me equivoquei, o arquivo correto seria o [index.html](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/index.html), pra tag ficar no `head`, acabou ficando no `body`