I18N - Home
okfn-brasil/querido-diario-frontend pull request #322
Opened 2024-11-18 03:00 UTC by MoisesMsa

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [ ] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/codigo-de-conduta.html).

## Tipo de alteração

* [ ] 🐞 Correção de problema
* [x] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
#163 

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [ ] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências
Anexe evidências do antes e do depois da alteração (quando necessário).
![home_i18n](https://github.com/user-attachments/assets/48539b34-0f79-471b-9249-a151d159b3d1)

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [x] Esta alteração requer que a documentação externa seja atualizada.

2024-11-18 03:17 UTC, MoisesMsa commented
Abri a PR porque está bem grande, como a #165 estava desatualizada a um tempo criei uma nova branch e optei por outra abordagem já que a maior parte das strings já estão mapeadas em um JSON (preciso fazer algumas melhorias quanto a isso pq algums arquivos compartilham infomações de ícones, estilos que precisei copiar pros arquivos localization para não quebrar a página). 
A ideia é criar as outras PRs a partir dessa com a tradução das outras páginas e dar uma revisada se as traduções estão boas porque acho que alguns termos precisam serem melhores adptados.

2024-11-18 18:19 UTC, lguima requested changes
muito bom, @MoisesMsa! excelente solução! :clap: 

reparei apenas que a gente traduziu a rota também, mas ela não existe em inglês, ai o link do cabeçalho fica quebrado

outro ponto é o layout mobile, foi intencional não cobrir nessa PR?

2024-11-18 18:19 UTC, lguima commented on src/assets/i18n/en/global.json
> +        "route": "/technology"
A rota `/technology` não existe, quebrando o link no header quando troca para inglês.

2024-11-18 21:45 UTC, MoisesMsa commented on src/assets/i18n/en/global.json
> +        "route": "/technology"
Opa, sobre o mobile sim foi intencional porque ia ficar muita coisa pra revisar, vou tratar em uma issue nova, ok?

2024-11-22 03:08 UTC, MoisesMsa commented
@lguima ajustei, as rotas de EN para as atuais em PT

2024-11-22 14:09 UTC, lguima approved these changes
LGTM :rocket:

2025-01-27 00:31 UTC, lguima commented
@ogecece @MoisesMsa bora retomar pra fechar essa funcionalidade?

2025-01-27 01:35 UTC, MoisesMsa commented
@lguima opa, bora. Essa semana consigo retomar

2025-02-17 12:26 UTC, MoisesMsa commented
@lguima resolvi o conflito, quando puder dar um check

2025-02-17 12:56 UTC, lguima commented
@MoisesMsa reparei que os textos dos campos de pesquisa ficaram sem tradução, mas acho que podemos abrir uma nova issue pra página de busca que cubra esses textos, como vc tá fazendo pras outras páginas, pra não bloquear a PR mais tempo

![Screenshot from 2025-02-17 09-49-29](https://github.com/user-attachments/assets/52511757-fa57-4bbf-b427-7c8f07b4e4f0)

![Screenshot from 2025-02-17 09-50-21](https://github.com/user-attachments/assets/a680a99f-5248-4d1c-9ec5-f39f082e9ae4)

![Screenshot from 2025-02-17 09-50-59](https://github.com/user-attachments/assets/d2042a14-aded-467d-8ad7-7ba03256c38c)

2025-02-17 13:07 UTC, MoisesMsa commented
blz

2025-02-25 13:22 UTC, merged

2025-02-26 20:24 UTC, trevineju commented
@MoisesMsa, @lguima tenho uma dúvida: 
No repo agora há 3 arquivos que alimentam o texto da home:
- em i18n, em ptbr: [home.json](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/assets/i18n/pt/home.json)
- em i18n, em eng: [home.json](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/assets/i18n/en/home.json)
- em assets/pages: [home.json](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/src/assets/pages/home.json) 

Como os que estão em i18n que são usados (certo?) o *assets/pages/home.json* está inutilizado? podemos remover do repositório?

2025-02-26 20:33 UTC, MoisesMsa commented
@trevineju pode remover sim, utilizei ele de base para os outros jsons.

2025-02-26 20:51 UTC, trevineju commented
Beleza, faço isso em seguida! 

Outra coisa, é que pelo print de evidência que deixou aqui notei que o contador de cidades na home quebrou. 

Daí, subi um fix provisório #357 e deixei uma issue #358 para ser arrumado depois. Entendi que era melhor fazer assim pois, conforme você e Lucas conversaram aqui, vocês vão seguir trabalhando nas traduções das outras páginas, certo? 
Aí para não tirar vocês do contexto, julguei que fazia sentido vocês seguirem aí e depois voltamos na correção pontualmente.

2025-02-26 21:07 UTC, MoisesMsa commented
Certo, muito obrigado. Vou dar um check na issue.