fix: Posicionamento dialog notificacao
okfn-brasil/querido-diario-frontend pull request #323
Opened 2024-11-25 01:19 UTC by devcaiosantos

Usando como referência o "botão"

**Português (BR)** | [English (US)](?quick_pull=1&template=PULL_REQUEST-en-US.md)

## Comunidade

* [x] Eu li e segui o [Guia de Contribuição](https://github.com/okfn-brasil/querido-diario-frontend/blob/main/docs/CONTRIBUTING.md).
* [x] Eu li e segui o [Código de Conduta](https://docs.queridodiario.ok.org.br/pt-br/latest/contribuindo/codigo-de-conduta.html).

## Tipo de alteração

* [x] 🐞 Correção de problema
* [ ] ✨ Melhoria ou nova funcionalidade
* [ ] 📰 Nova postagem no blog

## Issues relacionadas
#307 

## Validação

* [ ] Validei a alteração no link gerado pelo bot da Netlify (Deploy Preview/Preview on mobile)
* [x] Validei o Layout responsivo (desktop/mobile) após a implementação
* [ ] Verifiquei o registro do deploy (Latest deploy log) e nenhum novo alerta ou erro foi adicionado

## Evidências

Antes:
![image](https://github.com/user-attachments/assets/f8bb0d07-9745-4588-8f51-481a20dc2000)

Depois:
https://github.com/user-attachments/assets/3d2bd9e0-e616-438b-b7ea-ea62d9d2b9b7

## Documentação

* [ ] A documentação deste repositório foi atualizada (quando necessário).
* [ ] Esta alteração requer que a documentação externa seja atualizada.

2024-12-01 00:03 UTC, MoisesMsa requested changes

2024-12-01 00:03 UTC, MoisesMsa commented on src/app/modules/components/header/header.component.ts
> +  notificationPopoverRef: any;
Acho que dá para trocar o _any_ aqui por _MatDialogRef<NotificationsComponent> | null = null;_

2024-12-01 00:04 UTC, MoisesMsa commented
@devcaiosantos muito boa essa solução, solicitei apenas um ajuste por causa da tipagem do TS.

2024-12-03 02:55 UTC, MoisesMsa approved these changes

2024-12-11 18:03 UTC, ogecece commented
Fica à vontade pra mesclar @MoisesMsa !

2024-12-12 10:04 UTC, merged