adiciona mensagem de limite máximo de resultados
okfn-brasil/querido-diario-frontend pull request #37
Opened 2022-04-20 21:01 UTC by ArianeCamilo

Corrige #27 
Fixes #27

2022-05-09 21:18 UTC, giuliocc requested changes
Acho que a maneira que todos os condicionais das mensagens do arquivo estão feitos pode melhorar um pouco. Semana que vem damos uma olhada nesse PR e no #42

2022-05-21 18:15 UTC, lguima commented on src/app/pages/search/search.component.html
> + <!-- <ng-container
Por que deixar código comentado?
Se não está sendo usado, podemos remover e se precisarmos trazer de volta, está no histórico do Git.

2022-05-21 18:15 UTC, lguima commented on src/app/pages/search/search.component.html
> +    <div *ngIf="
Poderia ajustar a indentação para alinhar com o elemento pai?

2022-05-21 18:15 UTC, lguima commented on src/app/pages/search/search.component.html
> +    <ng-template #elseBlock>
Acho que não seria o caso de uma mensagem em detrimento da outra, talvez uma informação a mais no cenário de limite possa ser mais efetiva.

### **Sugestão**
Abaixo, estão os resultados encontrados nos diários dos municípios que já conseguimos disponibilizar em formato aberto! Assim você consegue realizar a busca nos documentos de um jeito fácil.

*_A quantidade de resultados atingiu o limite da busca que é de 10.000 registros. Tente digitar um termo mais específico ou usar mais de um para otimizar sua pesquisa._

2023-04-21 14:52 UTC, lguima commented on src/app/modules/pages/search/search.component.html
> +              *A quantidade de resultados atingiu o limite da pesquisa. Tente digitar um termo mais específico ou usar mais de um para otimizar sua busca.
@trevineju como o título da página é "busca avançada", coloquei o link de forma que utilize o mesmo termo:

> "[...] Tente utilizar termos mais específicos ou os operadores da busca avançada."

o que acha?

2023-04-26 12:04 UTC, merged