Corrige codificação de URL de requisição para API
okfn-brasil/querido-diario-frontend pull request #49
Opened 2022-05-27 18:25 UTC by giuliocc

Fixes #48

2022-05-27 18:27 UTC, giuliocc commented
### Português

@lguima você poderia revisar esse PR?

---

### English

@lguima could you review this PR?

2022-05-28 21:44 UTC, lguima commented
Você teria um exemplo de busca que mudou com essa implementação?

A citada na #48 não mudou no [preview da Netlify](https://deploy-preview-49--querido-diario-plataforma.netlify.app/).

![qd-query-string](https://user-images.githubusercontent.com/1562097/170843696-7d61a20e-6545-44e5-9984-4ce9751d0de0.png)

2022-07-01 22:05 UTC, giuliocc commented
@lguima desculpa a demora! A busca seria por `linux + windows` hahah

2022-07-02 19:04 UTC, lguima requested changes

2022-07-25 15:36 UTC, giuliocc commented on src/app/gazette.service.ts
> +      queryParams = { ...queryParams, territory_id: territory_id };
Essa não implementei pois o nome do argumento na API se tornou `territory_ids`, podendo aceitar mais de um município.

2022-07-25 15:37 UTC, giuliocc commented on src/app/gazette.service.ts
> +      queryParams = { ...queryParams, until: until };
Implementado :+1:

2022-07-25 15:37 UTC, giuliocc commented on src/app/gazette.service.ts
> +      queryParams = { ...queryParams, sort_by: sort_by };
Implementado :+1:

2022-07-25 15:37 UTC, giuliocc commented on src/app/gazette.service.ts
> +    const encoded_qs = new URLSearchParams(queryParams).toString();
Implementado :+1:

Boa!

2022-07-25 15:37 UTC, giuliocc commented on src/app/gazette.service.ts
> +    const url = `https://queridodiario.ok.org.br/api/gazettes?${encoded_qs}`;
Huuum legal! Não estava familiarizado com o uso adequado de URLs, obrigado!

Implementado :+1:

2022-07-25 15:39 UTC, giuliocc commented
@lguima muito obrigado pelo review! Não conhecia algumas coisas e implementei tudo que você pediu (somente um comentário que ficou defasado em relação aos avanços da API ficou de fora).

Mesclando agora o PR <3

2022-07-25 15:39 UTC, merged