Atualiza documentação
okfn-brasil/querido-diario-frontend pull request #60
Opened 2022-08-26 00:56 UTC by trevineju

Buscando se adequar ao padrão de documentação adotado no projeto, este PR:
- Move a licença para .github
- Ao invés de conter uma duplicação do texto do CONTRIBUTING.md do repositório de Comunidade, substitui o texto de CONTRIBUTING.md local para referenciá-lo.

2022-10-07 00:33 UTC, lguima commented
Aguardando a finalização do https://github.com/okfn-brasil/querido-diario-comunidade/pull/17 para caso seja necessário ajustar algo nesta PR.

2023-02-28 23:38 UTC, giuliocc requested changes
Algumas coisas notei que passaram no querido-diario. Vou modificar lá.

De resto, achei ótimo!

Alguns comentários de tradução eu fiz em um ponto só mas havendo outras ocorrências seria necessário replicar.

2023-02-28 23:38 UTC, giuliocc commented on docs/README.md
> +Com um terminal aberto no diretório do seu fork do repositório, use a sequência de comandos a seguir para instalar todas essas ferramentas em sistema operacional Linux:
```suggestion
Por meio de um terminal aberto no diretório raíz do repositório, use a sequência de comandos a seguir para instalar todas essas ferramentas em sistema operacional Linux:
```

2023-02-28 23:38 UTC, giuliocc commented on docs/README.md
> +$ yarn ng serve
```suggestion
1. Com o terminal aberto no diretório raíz do repositório, o projeto pode ser servido localmente com o comando:
``` console
yarn ng serve
```

2023-02-28 23:38 UTC, giuliocc commented on docs/README.md
> +✔ Compiled successfully.
```suggestion
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.
```

2023-03-06 17:43 UTC, trevineju commented on docs/README.md
> +# Querido Diário (frontend - interface web)
Commitei o título de volta ao formato anterior e já adicionei a menção à Jurema.

2023-03-17 14:21 UTC, giuliocc requested changes

2023-03-17 14:21 UTC, giuliocc commented on docs/CONTRIBUTING.md
> +6. Pronto! Agora você já pode começar a editar o código.
```suggestion
5. Pronto! Agora você já pode começar a editar o código.
```

2023-03-17 17:07 UTC, giuliocc approved these changes

2023-03-17 17:09 UTC, giuliocc commented
LGTM! Pode dar um squash?

2023-03-17 19:35 UTC, merged