Atualiza o README.md
okfn-brasil/querido-diario-frontend pull request #76
Opened 2022-09-29 21:02 UTC by trevineju

Este PR resolve uma das 8 tarefas da issue #https://github.com/okfn-brasil/querido-diario-comunidade/issues/15, implementando a documentação padronizada para o README.md neste repositório

2022-10-03 01:51 UTC, lguima requested changes
Oi, @trevineju, deixei algumas sugestões e observações :)

2022-10-03 01:51 UTC, lguima commented on README.md
> +Você encontra como fazê-lo no [CONTRIBUTING.md](.github/CONTRIBUTING.md)!
Faltou o texto do link e considero que apenas ponto final seja suficiente, a entonação maior já foi aplicada na frase anterior.

```suggestion
Você encontra como fazê-lo em nosso [Guia de Contribuição](.github/CONTRIBUTING.md).
```

2022-10-03 01:51 UTC, lguima commented on README.md
> +# Como configurar o ambiente de desenvolvimento
Acho que ficou extensa demais, com baby steps que para quem já mexe com JS é bem conhecido, acho que vale a gente colocar links para como instalar o Node com gerenciador de versão, para instalar o yarn que aí lá vai ter as especificidades de plataforma.

E focar o README como rodar mesmo o projeto em si, que não muda nada entre plataformas.

2023-02-22 22:08 UTC, trevineju commented
Conteúdo sendo desenvolvido neste PR foi centralizado em #60

2023-02-22 22:08 UTC, closed without merging