Atualiza informações do site em função da entrada de novas cidades (outubro/hacktoberfest/2022)
okfn-brasil/querido-diario-frontend pull request #83
Opened 2022-10-20 20:11 UTC by trevineju

Novas cidades: 
- Acajutiba-BA
- Belford Roxo-RJ
- Campinas-SP
- Joinville-SP
- Marília-SP
- Santo André-SP

2022-10-21 11:46 UTC, lguima commented
@trevineju é para PR ser mesclada somente quando tivermos a data de anúncio e as notificações incluídas?

2022-10-21 20:03 UTC, trevineju commented
isso

2022-11-11 22:07 UTC, trevineju commented
o PR agora atualiza todas as cidades que o QD tem em produção atualmente. Além das mencionadas acima, adiciona também:
- Caxias do Sul (RS)
- Santana (AP)
- Rondonópolis (MT)

2022-11-11 22:18 UTC, giuliocc requested changes
Só uma correçãozinha de escrita

2022-11-11 22:18 UTC, giuliocc commented on src/assets/pages/notifications.json
> +      "content": "A cidade de Joinville (SC), Marília (SP), Santana (AP) e Santo André (SP) foram adicionadas à plataforma!",
```suggestion
      "content": "As cidades de Joinville (SC), Marília (SP), Santana (AP) e Santo André (SP) foram adicionadas à plataforma!",
```

2022-11-11 22:18 UTC, giuliocc commented on src/assets/pages/notifications.json
> +      "content": "A cidade de Acajutiba (BA), Belford Roxo (RJ), Campinas (SP) e Rondonópolis (MT) foram adicionadas à plataforma!",
```suggestion
      "content": "As cidades de Acajutiba (BA), Belford Roxo (RJ), Campinas (SP) e Rondonópolis (MT) foram adicionadas à plataforma!",
```

2022-11-11 23:04 UTC, giuliocc approved these changes
LGTM!

2022-11-11 23:30 UTC, merged